name: Build and Test

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
        path: v

    - name: Checkout the module
      uses: actions/checkout@v2
      with:
        path: ~/.vmodules/spytheman/regex/

    - name: Install libpcre3-dev package
      run: sudo apt-get install --quiet -y libpcre3-dev

    - name: Build V
      run: cd v && make && sudo ./v symlink && cd -

    - name: V doctor
      run: v doctor

    - name: Ensure everything is formatted
      run: v fmt -verify ~/.vmodules/spytheman/regex/

    - name: Run tests
      run: v test ~/.vmodules/spytheman/regex/

    - name: Build example with -cstrict
      run: v -cstrict ~/.vmodules/spytheman/regex/examples/hello.v

    - name: Build example with -cstrict -prod
      run: v -cc gcc -cstrict -prod ~/.vmodules/spytheman/regex/examples/hello.v
